### ISSUE TITLE
Support resizable elements within dashboard cells

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#12]
The some urth widgets need to update their internal dimensions when their container is resized. This requires that we have some sort of event/notification other than window.onResize().

Our current idea is as follows:   There exists PolymerElement/iron-resizable-behavior, which adds a notifyResize() method to the element. We can listen in dashboard for when a cell is resized, then find any polymer elements contained within, and if they implement this behavior, we notifyResize on them so that they can then resize appropriately.

The problem from the Dashboard side is how do we query for Polymer elements and find out if they implement/mixin the iron-resizable-behavior?

**Comment by parente** [comment]
@dalogsdon says:

We could just look at each direct-child of the output_area and widget-area in the cells, and see if they implement notifyResize(). This would cut down on the number of elements we'd have to search for.

**Comment by lbustelo** [comment]
Searching is probably not a viable solution. 
In looking at the iron-resizable-behavior code, the best thing would be to attach a listener for 'iron-request-resize-notification' to each output area or other higher up element. That is the way that resizable elements let the world know about them. Then keep a running list. 

An easier approach would be to have control of the created Dom and insert resizable aware elements, but this would mean a deeper tie into polymer. 

Gino B.

**Comment by jhpedemonte** [comment]
Attached a pull request which updates the Dashboard code based on Gino's comment above. We tested with the following notebook: https://gist.github.com/jhpedemonte/d07b269b3f9b6dc8f8b3. Switching between Notebook and Dashboard views should notify the element to resize, as well as resizing the window or the cell (when in dashboard view).

In order to work with this code, Polymer elements will need to mixin `iron-resizable-behavior` and listen for the `iron-resize` event.

**A note on sizing relative to the notebook/dashboard cell:**
A dashboard cell has an exact width and height specified by the user. However, because a notebook cell's *height* is determined by its children's height (`widget-area` and `output_area`), an element cannot set its height relative to the notebook cell.
