### ISSUE TITLE
Broken link in the binder app

### ISSUE THREAD

**Issue by SimonBiggs** [jupyter-incubator/dashboards#162]
Within the try it example found at:
http://mybinder.org/repo/jupyter-incubator/showcase

The "Introduction to Dashboards" link is broken:
http://app.mybinder.org/3477095624/notebooks/dashboards/index.ipynb

**Comment by parente** [comment]
I've had this happen a few times where, apparently, the binder image gets rebuilt using only the requirements.txt file instead of the Dockerfile. As a result, none of the demo notebooks get cloned in from the other repos.

I'm not sure if it's some auto rebuild every time binder gets redeployed or the base image updates or someone goes to the binder site to rebuild it incorrectly. At any rate, I manually triggered another rebuild with the Dockerfile setting properly selected and all seems well now again.

**Comment by SimonBiggs** [comment]
Weird, thanks for that. :)
