### ISSUE TITLE
Associations link broken within binder app within index.ipynb

### ISSUE THREAD

**Issue by SimonBiggs** [jupyter-incubator/dashboards#163]
Associations demo link bug has not carried through into the binder app demo.
The notebook here:
http://app.mybinder.org/2562667438/notebooks/dashboards/index.ipynb
Has the following link:
http://app.mybinder.org/2562667438/notebooks/dashboards/associations_demo/associations_demo.ipynb

This was fixed in the following commit however is not fixed in the binder app:
https://github.com/jupyter-incubator/dashboards/commit/931b844a178111d9d6416d50e439bda957e79993

**Comment by parente** [comment]
The binder base image uses IPython Notebook 3.2.x. Only the 0.1.x series of releases of this extension are compatible with that version of notebook. The fix for the notebook name came after that point.

As a quick fix, I can modify the Dockerfile over in showcase to correct the path. Longer term, we'll benefit from Binder moving to Notebook 4.x (which would allow us to install our newer versions which fix a variety of other problems). In the meantime, we can figure out where to put the automation for the tmpnb-based http://jupyter.cloudet.xyz site we're running specifically for the dashboard-related incubator projects. (It too is backlevel on IPython 3.2.1 but something we more directly control and can upgrade.)

**Comment by parente** [comment]
I stand corrected: the notebook fix is in the 0.1.1 release too. It was cherry-picked across so the commit SHA linked above doesn't show it in the 0.1.x branch.

I bumped the dashboards and declarativewidgets package versions in the showcase to 0.1.1 and rebuilt the binder. All set for now.
