### ISSUE TITLE
Cell bounding box ignored in Layout view

### ISSUE THREAD

**Issue by jtyberg** [jupyter-incubator/dashboards#194]
I'm trying to arrange some visible cells in Layout view, but I'm seeing some strange behavior with one cell in particular.  It's as though the bounding box for the cell is unknown (or being ignored).  So when I try to arrange it, other cells are not pushed down to make room for it, which causes cells to overlap.  When I try to resize it, it just snaps back to original size. 

![dash_bbox_issue](https://cloud.githubusercontent.com/assets/359081/13162104/8aaa6a64-d670-11e5-90b2-f7bafb1cfc64.gif)

**Comment by jtyberg** [comment]
I just tried hiding the cell, then adding it back as a visible cell, and the problem "fixed" itself.  Grr?

**Comment by parente** [comment]
I've seen this before and I've never found a way to reproduce it reliably.

We're going to cut a 0.4.2 release soon with a new version of gridstack. Let's keep this open and see if it surfaces again. If it does, I suspect it's a timing issue with computing the position of cells as the notebook is flipping over to layout mode. We've addressed a few of these in the past. There might be one lurking.

**Comment by parente** [comment]
I believe this is caused by refreshing the page when in dashboard preview mode (i.e., when `?dashboard` is on the end of the URL). I hit it multiple times when testing the PRs for #55 . I also haven't seen it again after those PRs went into master, even when refreshing in dashboard view many times and switching between layout, preview, and notebook. 

The report mode implementation refactored and improved a lot of code related to switching modes.

**Comment by dalogsdon** [comment]
Indeed I encountered this during report layout work and fixed a few issues that were causing this behavior. Unfortunately I did not note them nor do I remember how to reproduce.

**Comment by parente** [comment]
I've not hit this since 0.5.0, and not for lack of trying. I think it's now safe to close. We'll reopen if it reappears.
