### ISSUE TITLE
Dragging to edge of browser does not scroll browser

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#198]
Try to drag a cell past the bounding box of the current browser viewport in a large dashboard that extends past the browser view. The browser viewport does not scroll. Have to drop the cell, manually scroll the browser, pick it up again, drag, repeat.

**Comment by dalogsdon** [comment]
This was really bugging me yesterday when I tried to make a long dashboard to test page height.

**Comment by dalogsdon** [comment]
Looks like I can add some edge scrolling code using a Gridstack 'drag' event handler the same way we add the 'dragstop' handler in [dashboard.js](https://github.com/jupyter-incubator/dashboards/blob/master/jupyter_dashboards/nbextension/notebook/dashboard-view/dashboard.js#L173).

**Comment by dalogsdon** [comment]
This is getting a little bit complicated due to the notebook structure. The main difficulty is that the element that scrolls is `#site` while the Gridstack content is 4 levels down in `#notebook-container`. Several containers in this hierarchy are absolutely sized to give the desired notebook layout and scroll functionality. This structure causes some issues.

1. Gridstack uses jQuery UI draggable, which supports edge scrolling via the 'scroll' option. Under simpler circumstances this works fine for Gridstack, but the complexity of the notebook page breaks this functionality. Gridstack normally also works as expected when manually scrolling with the mouse while dragging an element, but this is also broken by the notebook structure. I validated this by moving the container top-level in the document body and observing proper scrolling behavior. We don't want to modify the notebook structure, however.

2. If I manually update the `scrollTop` property of `#site` I can edge scroll the container properly, but the selected element remains at its position in the grid and scrolls out of sight, making the scrolling useless. The CSS position cannot be reliably updated by hand as jQuery has a tight grip on it while dragging and will reset it to its original position. I'm still looking to see if this is possible without digging too far into jQuery.

**Comment by dalogsdon** [comment]
Came across [this jQuery UI doc](http://api.jqueryui.com/draggable/#event-drag) for draggable event. Looks like I can use the `ui` object for custom position setting. It only seems to be mentioned in the 1.11 docs, but it seems to work in 1.10.
