### ISSUE TITLE
Dashboard layout cells should have "move" buttons

### ISSUE THREAD

**Issue by dalogsdon** [jupyter-incubator/dashboards#208]
From comments in #205:

> https://github.com/jupyter-incubator/dashboards/pull/205#issuecomment-201970944 - @parente: If I want to quickly move a cell that is already in the layout to the top, bottom, or natural cell order, I first have to remove it from the layout in order to use the + buttons. That seems wrong. Should we have the same move shortcut buttons appear on cells already in the layout?

> https://github.com/jupyter-incubator/dashboards/pull/205#issuecomment-202458765 - @jhpedemonte: We would also have to disable the relevant icon if the cell is already in that position (i.e. if at top, disable "move to top" button; might be interesting for cell order button).

**Comment by dalogsdon** [comment]
I agree that it should include top and bottom, but does it make sense to also include notebook cell order once a cell is already somewhere in the dashboard?

**Comment by parente** [comment]
> I agree that it should include top and bottom, but does it make sense to also include notebook cell order once a cell is already somewhere in the dashboard?

Good point. I can't think of a situation where I put it in notebook order, then somehow it gets out of order, and I have to put it back.

**Comment by parente** [comment]
I think we should retarget this and the other minor tweaks to 0.5. We're not in a dire rush to release at the moment.

**Comment by dalogsdon** [comment]
Corner of cells is now like:

![image](https://cloud.githubusercontent.com/assets/6362426/14266443/dd650fc0-fa8d-11e5-8614-f3bf48edcf52.png)

**Comment by parente** [comment]
Merged the PR with the move top / bottom buttons. I think I was wrong about leaving out the move to notebook position option for 2 reasons:

1. If I accidentally click top/bottom, I have to hide the cell in order to get the button to appear to get it back into notebook position.
2. The asymmetry of options bothers me.

No need to tackle for now. Let's leave it as-is and see if anyone reports the missing third option as a problem.
