### ISSUE TITLE
Grid: Hide cell doesn't save grid metadata

### ISSUE THREAD

**Issue by dalogsdon** [jupyter-incubator/dashboards#248]
`notebook-metadata.save()` will copy gridstack data from cell attributes to cell metadata. The save function is called on various actions done on the grid cells, but not on cell hide. To reproduce:

1. Create a grid layout dashboard with a full-width cell at the top
2. Hide that top full-width cell
3. Immediately either save the notebook or deploy to dashboard server
4. In the notebook file, notice the cell grid layout metadata is incorrect
5. In the dashboard server, notice the dashboard contents are shifted down the page as if the original top cell is invisible at the top of the dashboard

**Comment by parente** [comment]
> In the notebook file, notice the cell grid layout metadata is incorrect

What does "incorrect" mean here?  I see an empty layout object but everything else seems fine. 

If that's incorrect, then this is due to the 11th hour fix I had to put in for report mode layouts going lost. We agreed presence of `layout` is the flag (for the time being) meaning that a cell has been seen by the layout extension in the past and should not be automatically laid out again. This fixed report mode from going missing on save.

I don't see the space reserved in dashboard preview, but I do in dashboard server. I think the fix here is going to have to be against dashboard server, to first consider objects with hidden: true as hidden and only then considering what an empty layout object might mean.

**Comment by parente** [comment]
Nevermind. I see the problem now. It's not the cell that was hidden that has the wrong metadata. It's the ones below it that get recomputed but not saved.

**Comment by dalogsdon** [comment]
Yes, sorry, the cells still in the grid have the wrong position values.
