### ISSUE TITLE
Multiple Instances of Dom Nodes In Dashboard View

### ISSUE THREAD

**Issue by Lull3rSkat3r** [jupyter-incubator/dashboards#42]
When working with the Commnunity Sentiment Notebook multiple dom nodes are created for the `urth-core-function` elements in dashboard view.  It appears there are multiple instances of the notebook represented in gridstack, as well as duplication of the cells within a given output area.

When I reference an element by its id, I see an array returned.
<img width="648" alt="multiple dom nodes" src="https://cloud.githubusercontent.com/assets/1383927/10620039/9dc15d24-773e-11e5-97a8-e794f066324c.png">

The dom nodes are in the page in various places
One by itself:
<img width="1569" alt="first dom node" src="https://cloud.githubusercontent.com/assets/1383927/10620058/b275b8fa-773e-11e5-8f27-085b3da09a23.png">

And two within the same output area
<img width="1569" alt="dom nodes within same output" src="https://cloud.githubusercontent.com/assets/1383927/10620062/b81234c8-773e-11e5-8ce0-48fa5612503a.png">

The kicker is I can reproduce using the following code in that notebook:
```html
%%html
<div id='baz'></div>
```
```javascript
//i in dashboard mode
baz.length === 2 // true
```
However, if I start in a fresh notebook the problem doesn't happen.

**Comment by dalogsdon** [comment]
We would duplicate it once when we clone hidden cells to show in the hidden area. I am not sure where a third one comes from.

**Comment by jhpedemonte** [comment]
This is caused by how we show the cells in the **hidden section** of the dashboard. Our main goal is to show a visual representation of the cells (if they have any output). We first tried to move them from their area in the notebook to the hidden section (and allow moving back), but this breaks Notebook functionality.

In the end, we just duplicated the DOM (but not events and data). That's why there's more than 1 cell with an ID.  Not sure how else we would handle this and still show a cell's visual output in the hidden area.

**Comment by jhpedemonte** [comment]
It seems like we would want to go away from copying the DOM, since it can have bad implications. Some options we thought of as replacements:

1. Only show code in the hidden section. Default to showing the first 5 or 10 lines, but allow user to expand. If user wants to see what that cell outputs, they can either add the cell to the dashboard or click on the *edit* button to go back to the Notebook view.
2. Use [html2canvas](http://html2canvas.hertzen.com/), which attempts to recreate an element's DOM and render it visually. This would allow us to show "screenshots" in the hidden section. Main downside is that this does a recreation of the DOM; it doesn't image the actual cell's DOM. That means there could be inconsistencies with rendering.

Any other suggestions?

**Comment by jhpedemonte** [comment]
Another option:
3. Create another Gridstack which would absolutely position the `hidden` elements. The main issue here is that both Gridstack instances would use the same container (since we can't move any of the Notebook cells). That means they would overlap -- we'd have to add JavaScript to continually reset the height offset of the `hidden` Gridstack.
