### ISSUE TITLE
Prevent accidental add all / remove all cells from dashboard

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards#99]
If I click either eyeball icon accidentally, my dashboard is pretty much destroyed and I have to lay it all out again. Should we warn the user and give him/her a way to back out (but I hate modal dialogs)? Enable undo (tricky)? Remove these options entirely (but we added them for good reason, right)?

**Comment by dalogsdon** [comment]
If they are not going to be common actions, we could relegate them to a menu so it is less likely to accidentally hit.

Alternatively, I would vote for either a normal undo since the notebook already has undo functionality (and explicitly calls out what to undo in the menu, e.g. "undo delete cell") or a non-intrusive non-modal undo dialog like in Gmail:

![image](https://cloud.githubusercontent.com/assets/6362426/10911912/9e4be7ae-820c-11e5-9fc4-fe719d34bf00.png)

**Comment by jhpedemonte** [comment]
Agree with Drew: move to menus (since these are less often used) and make use of undo stack. No warning dialogs, please.

**Comment by jhpedemonte** [comment]
Jupyter doesn't have an undo stack. Undoing text editing (within cells) is handled by the browser itself. The only thing Jupyter seems to provide is **Undo Delete Cell**.

So if we want to handle undo/redo of Dashboard operations, we'd have to create out own undo stack. But I would advise against this and instead push for a true undo/redo system to be added to the base Jupyter code.

**Comment by parente** [comment]
Punt on the undo / redo. I think that's come up a few times against the notebook proper. Moving to menu to avoid accidental click is a good first step.
